name: Build
on:
  schedule:
    - cron: '31 * * * *'
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}/${{ github.ref_type }}/${{ github.ref_name }}
  cancel-in-progress: true
permissions:
  contents: none
  deployments: none
  actions: none
  checks: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  version:
    name: Get Version
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Upstream Repo
        uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          submodules: recursive
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y make git zlib1g-dev libssl-dev gperf cmake g++
      - name: Inject Version CMake Command
        run: |
          echo 'file(WRITE version.txt "${PROJECT_VERSION}")' >> CMakeLists.txt
          cat CMakeLists.txt
      - name: Run CMake
        working-directory: build
        id: version
        run: |
          tmp_dir=$(mktemp -d)
          cmake -B "$tmp_dir" -S .. ..
          version="$(cat ../version.txt)"
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Debug
        run: |
          echo "version=${{ steps.version.outputs.version }}"
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    needs:
      - version
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout Upstream Repo
        uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          path: upstream
          submodules: recursive
          fetch-depth: 0
      - name: Get Version
        working-directory: upstream
        id: version
        run: |
          telegram_bot_api_rev="$(git rev-parse --short HEAD)"
          echo "telegram_bot_api_rev=${telegram_bot_api_rev}" >> $GITHUB_OUTPUT
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=${{ github.event.repository.default_branch }}
            type=raw,value=${{ steps.version.outputs.telegram_bot_api_rev }}
            type=raw,value=${{ needs.version.outputs.version }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
          flavor: |
            # See https://github.com/docker/metadata-action#latest-tag
            latest=${{ github.ref_name == github.event.repository.default_branch }}
            prefix=,onlatest=false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Image Build and Push
        id: docker_build_and_push
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          no-cache: true
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
        timeout-minutes: 90
