name: Build
on:
  schedule:
    - cron: '31 13 * * *'
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}/${{ github.ref_type }}/${{ github.ref_name }}
  cancel-in-progress: true
permissions:
  contents: none
  deployments: none
  actions: none
  checks: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout Upstream Repo
        uses: actions/checkout@v4
        with:
          repository: tdlib/telegram-bot-api
          path: upstream
          submodules: recursive
          fetch-depth: 0
      - name: Get Version
        working-directory: upstream
        id: version
        run: |
          telegram_bot_api_version="$(git rev-parse --short HEAD)"
          tdlib_version="$(cd td && git rev-parse --short HEAD)"
          version="${telegram_bot_api_version}-${tdlib_version}"
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge,branch=${{ github.event.repository.default_branch }}
            type=raw,value=${{ steps.version.outputs.version }}
          labels: |
            maintainer=${{ github.repository_owner }}
            org.opencontainers.image.authors=${{ github.repository_owner }}
          flavor: |
            # See https://github.com/docker/metadata-action#latest-tag
            latest=${{ github.ref_name == github.event.repository.default_branch }}
            prefix=,onlatest=false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Image Build and Push
        id: docker_build_and_push
        uses: docker/build-push-action@v6
        with:
          push: true
          pull: true
          no-cache: true
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
        timeout-minutes: 90
